config/routes.rb
Rails.application.routes.draw do
  get '/', to: redirect('/home')
  get 'home' => "tiny_urls#home"
  post 'get_tiny_url' => "tiny_urls#get_tiny_url"
  match '*a' => "tiny_urls#get_orginal_url", :via => [:get]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/decodable.rb
module Decodable
  extend ActiveSupport::Concern
  # Total charecter to encode base to str
  @@total_char = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  @@total_char_hash = Hash[@@total_char.chars.map.with_index.to_a]
  @@rand_str_len = 1

  # It will convert id to base 62 and assign char from
  # @@total char and add rand str
  def genrate_short_url(url_id)
    rand_str = get_rand_str
    shorturl = Array.new
    while url_id != 0
      char_index = (url_id%62).to_i
      shorturl.push(@@total_char[char_index])
      url_id = url_id/62
    end
    base_str = shorturl.reverse!.join
    rand_str+base_str
  end

  #method to get random char
  def get_rand_str
    SecureRandom.hex(@@rand_str_len)
  end

  class_methods do
    #method to remove random str from url code
    def get_decoded_url(path_after_base_url)
      path_after_base_url.slice!(3..-1)
    end

    #method to deocde in base 10
    def get_url_id(decoded_url)
      decoded_url.reverse!
      url_id = 0
      decoded_url.each_char.with_index do |char, i|
        url_id += @@total_char_hash[char].to_i* (62 ** i)
      end
      url_id
    end
  end

end

app/models/tiny_url.rb
class TinyUrl < ApplicationRecord
  include Decodable
  validates :orginal_url, :format => URI::regexp(%w(http https))
  after_find :add_last_hit
  after_create :set_decode_url

  def add_last_hit
    self.last_hit = Time.now.strftime("%d/%m/%Y %H:%M")
    self.save
  end

  def set_decode_url
    self.generated_url = genrate_short_url(self.id)
    self.save
  end

  def self.get_tiny_url_by_path(path_after_base_url)
    coded_url = get_decoded_url(path_after_base_url)
    url_id = get_url_id(coded_url)
    self.find(url_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tiny_urls_controller.rb
class TinyUrlsController < ApplicationController
  skip_before_action :verify_authenticity_token
  layout "tiny_url"
  include CodeDecodeUrlModule

  # method to show home view
  def home
    @tiny_url = TinyUrl.new
  end

  # method to generate short url by decoding id
  def get_tiny_url
    @tiny_url = TinyUrl.new
    begin
      @full_url = ''
      original_url = tiny_url_params[:orginal_url]
      @tiny_url.orginal_url = original_url
      @tiny_url.system_info = request.remote_ip
      if @tiny_url.save!
        base_url = get_base_url
        @full_url = base_url+'/'+@tiny_url.generated_url
      end
      respond_to do |format|
        format.json{
          render :json => {tiny_url: @full_url, status: 'success', status_code: 200}
        }
        format.js{}
      end
    rescue Exception => e
      respond_to do |format|
        format.json{
          render :json => {error: e, status: 'error'}
        }
        format.js{}
      end
    end
  end

  #method to orginal url by decoding code to id
  def get_orginal_url
    begin
      path_after_base_url = request.original_fullpath
      @tiny_url = TinyUrl.get_tiny_url_by_path(path_after_base_url)
      redirect_to @tiny_url.orginal_url
    rescue Exception => e
      flash[:danger] = "Somthing wrong! Url not found"
      redirect_to home_path
    end

  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def tiny_url_params
    params.require(:tiny_url).permit(:orginal_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tiny_urls_helper.rb
module TinyUrlsHelper
end

app/views/layouts/tiny_url.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title>Easy Url</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= stylesheet_link_tag :application, media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag :main, media: 'all', 'data-turbolinks-track' => true %>
    <%= yield :page_level_style %>
    <!-- Scripts -->
    <%= javascript_include_tag :application %>
    <%= yield :page_level_script %>
  </head>
  <body>
    <!-- Header -->
    <header id="header">
      <div class="inner">
        <%= link_to raw("<strong>Projection</strong> by TEMPLATED"), home_path, class:"logo" %>
        <nav id="nav">
          <%= link_to "Home", home_path %>
        </nav>
        <a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
      </div>
      <% flash.each do |key, value| %>
        <div class="notice-div alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </header>
    <!-- Banner -->
    <section id="banner">
      <div class="inner">
        <header>
          <h1>Welcome to easy url</h1>
        </header>
        <div class="flex ">
          <div>
            <span class="icon fa-car"></span>
            <h3>Aliquam</h3>
            <p>Suspendisse amet ullamco</p>
          </div>
          <div>
            <span class="icon fa-camera"></span>
            <h3>Elementum</h3>
            <p>Class aptent taciti ad litora</p>
          </div>
          <div>
            <span class="icon fa-bug"></span>
            <h3>Ultrices</h3>
            <p>Nulla vitae mauris non felis</p>
          </div>
        </div>
        <footer>
          <a href="javascript:void(0)" class="button" id="get_start_button">Get Started</a>
        </footer>
      </div>
    </section>
    <%= yield %>
    <!-- Three -->
    <section id="three" class="wrapper align-center">
      <div class="inner">
        <div class="flex flex-2">
          <article>
            <div class="image round">
              <%= image_tag 'pic01.jpg' %>
            </div>
            <header>
              <h3>Lorem ipsum<br />
                dolor amet nullam</h3>
            </header>
            <p>Morbi in sem quis dui placerat ornare. Pellentesquenisi<br />
              euismod in, pharetra a, ultricies in diam sed arcu. Cras<br />
              consequat  egestas augue vulputate.</p>
            <footer>
              <a href="#" class="button">Learn More</a>
            </footer>
          </article>
          <article>
            <div class="image round">
              <%= image_tag 'pic02.jpg' %>
            </div>
            <header>
              <h3>Sed feugiat<br />
                tempus adipicsing</h3>
            </header>
            <p>Pellentesque fermentum dolor. Aliquam quam lectus<br />
              facilisis auctor, ultrices ut, elementum vulputate, nunc<br />
              blandit ellenste egestagus commodo.</p>
            <footer>
              <a href="#" class="button">Learn More</a>
            </footer>
          </article>
        </div>
      </div>
    </section>
    <!-- Footer -->
    <footer id="footer">
      <div class="inner">
        <h3>Get in touch</h3>
        <div>
          <div class="field half first">
            <label for="name">Name</label>
            <input name="name" id="name" type="text" placeholder="Name">
          </div>
          <div class="field half">
            <label for="email">Email</label>
            <input name="email" id="email" type="email" placeholder="Email">
          </div>
          <div class="field">
            <label for="message">Message</label>
            <textarea name="message" id="message" rows="6" placeholder="Message"></textarea>
          </div>
          <ul class="actions">
            <li><input value="Send Message" class="button alt" type="submit"></li>
          </ul>
        </div>
        <div class="copyright">
          &copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a href="https://unsplash.com">Unsplash</a>.
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/shared/_error.js.erb
$(".add-crud-edit-errors").empty();
$('<div>', {
    id: 'error_explanation_edit'
}).append($('<div>', {
    id: 'error-edit-inner-div',
    class: "alert alert-danger"
})).appendTo('.add-crud-edit-errors');
var list = $("#error-edit-inner-div").append('<ul></ul>').find('ul');
<% obj.errors.full_messages.each do |msg| %>
list.append("<h4 class='text-for-errors'><%= msg.humanize %></h4>");
<% end %>

app/views/tiny_urls/get_tiny_url.js.erb
$('#easy-url-div').empty();
<% if @tiny_url.errors.any?%>
  <%= render partial: "shared/error", locals: {obj: @tiny_url} %>
<% else %>
$('#easy-url-div').html("<%= escape_javascript render(:partial => 'tiny_urls/partials/easy_url', :locals => { :full_url => @full_url}) %>");
<% end %>

app/views/tiny_urls/home.html.erb
<section id="three" class="wrapper align-center">
  <div id="easy-url-error" class="add-crud-edit-errors">
  </div>
  <div class="inner">
    <%= form_for @tiny_url, :url =>get_tiny_url_path, :method => 'post', :remote => true, :authenticity_token => true do |f|%>
      <div class="field half first">
        <%= f.text_field :orginal_url, placeholder: "Paste Here Your Long Url", :required => true%>
      </div>
      <ul class="actions">
        <footer>
          <%= submit_tag "Get Easy Url", :id => "submit_button" %>
        </footer>
      </ul>
    <% end %>
    <div id="easy-url-div" class="">
    </div>
  </div>
</section>

app/views/tiny_urls/partials/_easy_url.html.erb
<h3>Your easy url is here ! Click it</h3>
<a href="<%= full_url%>" target="_blank"><span class="easy-url-span"><%= full_url%></span></a>